export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN_AKADEMIK: 'ADMIN_AKADEMIK',
  ADMIN_LMS: 'ADMIN_LMS',
  DOSEN: 'DOSEN',
  DOSEN_WALI: 'DOSEN_WALI',
  MAHASISWA: 'MAHASISWA',
  CALON_MAHASISWA: 'CALON_MAHASISWA',
  USER_UMUM: 'USER_UMUM',
};

export const ALL_ROLES = Object.values(ROLES);
